### ISSUE TITLE
Unrecognized function or variable 'numElems2'

### ISSUE THREAD

**Issue by ericleonardo** [Gu-X/Multi-Layer-Ensemble-Evolving-Fuzzy-Inference-System#1]
Hi!
Please, how can I fix this error when running the demo?

>> Demo_Classification
Unrecognized function or variable 'numElems2'.

Error in Demo_Classification (line 15)
for ii=1:1:numElems2

Thank you for sharing this great algorithm and paper!!

**Comment by Gu-X** [comment]
Hi, 

numElems2 should be 4. Thanks for spotting this.

The codes have been updated.

Thanks.

**Comment by ericleonardo** [comment]
Now it works!
Thank you : )
